# -*- coding: utf-8 -*-
"""bfs_spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTK-NKrtsnM_v4m4iB3K0k7A54xOn7g5
"""

# module_m2_spread/bfs_spread.py
import json
import numpy as np
from collections import deque


class BFSFireSpread:

    def __init__(self, graph_data_path):
        """[자료구조] JSON 그래프 데이터를 로드하여 2D 격자(Grid) 공간으로 추상화"""
        with open(graph_data_path, "r", encoding="utf-8") as f:
            self.raw_data = json.load(f)

        self.width = self.raw_data["simulation_settings"]["grid_width"]
        self.height = self.raw_data["simulation_settings"]["grid_height"]

        # 2D 인구 밀도 매트릭스 초기화 (60x60)
        self.population_matrix = np.zeros((self.height, self.width))
        for node in self.raw_data["nodes"]:
            x, y = node["grid_x"], node["grid_y"]
            self.population_matrix[y, x] = node["population_density"]

    def run_bfs(self, start_node_id, max_time=15):
        """[알고리즘] 큐(Queue) 자료구조 기반의 너비 우선 탐색(BFS) 화재 확산 시뮬레이션"""
        # 🔗 [연결부 매핑] 그래프 노드 ID -> 격자 좌표(x, y) 역산
        start_x = start_node_id % self.width
        start_y = start_node_id // self.width

        # -1.0은 아직 불길이 도달하지 않은 안전 구역을 의미
        fire_map = np.full((self.height, self.width), -1.0, dtype=float)

        # BFS 구현을 위한 큐(Queue) 선언: (현재_y, 현재_x, 도달_시간)
        queue = deque([(start_y, start_x, 0.0)])
        fire_map[start_y, start_x] = 0.0

        # 대각선 포함 상하좌우 8방향 탐색 오프셋
        directions = [
            (-1, 0), (1, 0), (0, -1), (0, 1),
            (-1, -1), (-1, 1), (1, -1), (1, 1)
        ]

        while queue:
            curr_y, curr_x, curr_t = queue.popleft()

            # [버그 수정 1] 큐에서 나온 값이 그사이 더 짧은 경로로 갱신되었다면 이전 쓰레기 값은 패스
            if curr_t > fire_map[curr_y, curr_x]:
                continue

            for dy, dx in directions:
                next_y, next_x = curr_y + dy, curr_x + dx

                # 격자 경계선 내부 검사
                if 0 <= next_y < self.height and 0 <= next_x < self.width:
                    pop_weight = self.population_matrix[next_y, next_x]

                    # [가중치 부여] 인구 밀집 구역은 확산 속도 가속(0.2초 추가), 공터는 일반 확산(1.0초 추가)
                    speed_weight = 0.2 if pop_weight > 0 else 1.0
                    next_t = curr_t + speed_weight

                    # [버그 수정 1] 제한 시간을 넘는 확산은 애초에 큐에 넣지 않음
                    if next_t > max_time:
                        continue

                    # [버그 수정 2] 아직 방문 안 했거나(-1.0), 새로 계산한 도달 시간(next_t)이 기존 도달 시간보다 더 빠른 경우 갱신
                    if fire_map[next_y, next_x] == -1.0 or next_t < fire_map[next_y, next_x]:
                        fire_map[next_y, next_x] = next_t
                        queue.append((next_y, next_x, next_t))

        return fire_map