# -*- coding: utf-8 -*-
"""ui_spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXSJ7EzOEA7qW7IasBfey-ZLkSkUzutD
"""

# module_m2_spread/ui_spread.py
import streamlit as st
import numpy as np
import plotly.graph_objects as go

from core.map_util import render_module_guide
from core.viz_util import style_fig, show

# 같은 패키지 폴더 내의 모듈들 로드 (상대 경로로 안전하게 변경)
from .bfs_spread import BFSFireSpread
from .cellular_automata import CellularAutomataModel

# 데이터 로드 캐싱 (성능 최적화)
@st.cache_resource
def init_simulation_engine():
    # 전처리 완료된 데이터 경로 지정 (실제 경로에 맞게 팀원들과 조율 가능)
    return BFSFireSpread("data/graph_data.json")

_HAZARD_COLORSCALE = [
    [0.00, "rgba(0,0,0,0)"],   # 0 안전 → 투명(페이지 배경)
    [0.33, "rgba(0,0,0,0)"],
    [0.34, "#FEE08B"],         # 1 주의
    [0.66, "#FC8D59"],         # 2 위험
    [1.00, "#990000"],         # 3 재난
]


def _build_spread_animation(fire_time_map, population_matrix, max_time):
    """BFS 도달시간 맵 → 시간별 확산 애니메이션 Plotly figure.
    프레임 t: fire_time_map <= t 인 셀만 표시(확산), 경과시간으로 단계 상승(심화)."""
    import numpy as np

    steps = [round(s, 1) for s in np.linspace(1, max_time, 20)]

    def hazard_at(t):
        z = np.zeros_like(fire_time_map, dtype=float)
        reached = (fire_time_map >= 0) & (fire_time_map <= t)
        elapsed = t - fire_time_map
        z[reached] = 1
        z[reached & (elapsed >= max_time * 0.3)] = 2
        z[reached & (elapsed >= max_time * 0.6)] = 3
        return z

    # trace0 = 인구 배경, trace1 = hazard(애니메이션 대상)
    fig = go.Figure(
        data=[
            go.Heatmap(z=population_matrix, colorscale="Greys",
                       showscale=False, opacity=0.12, hoverinfo="skip"),
            go.Heatmap(z=hazard_at(steps[0]), zmin=0, zmax=3,
                       colorscale=_HAZARD_COLORSCALE, showscale=False, hoverinfo="skip"),
        ],
        frames=[
            go.Frame(
                data=[go.Heatmap(z=hazard_at(t), zmin=0, zmax=3,
                                 colorscale=_HAZARD_COLORSCALE, showscale=False, hoverinfo="skip")],
                traces=[1],           # ← hazard 레이어만 갱신 (배경 유지)
                name=str(t),
            )
            for t in steps
        ],
    )

    # 범례용 더미 마커 (값 없음, 색상 안내만)
    for color, label in [("#FEE08B", "주의"), ("#FC8D59", "위험"), ("#990000", "재난")]:
        fig.add_trace(go.Scatter(
            x=[None], y=[None], mode="markers",
            marker=dict(size=12, color=color, symbol="square"), name=label,
        ))

    fig.update_layout(
        showlegend=True,
        legend=dict(orientation="h", y=1.08, x=1, xanchor="right", title=""),
        updatemenus=[{
            "type": "buttons", "showactive": False, "x": 0.0, "y": 1.12, "xanchor": "left",
            "buttons": [
                {"label": "▶ 재생", "method": "animate",
                 "args": [None, {"frame": {"duration": 350, "redraw": True},
                                 "fromcurrent": True, "transition": {"duration": 0}}]},
                {"label": "⏸ 정지", "method": "animate",
                 "args": [[None], {"frame": {"duration": 0, "redraw": False}, "mode": "immediate"}]},
            ],
        }],
        sliders=[{
            "active": 0, "x": 0.1, "len": 0.9, "y": 0, "pad": {"t": 5},
            "currentvalue": {"prefix": "경과 시간: ", "suffix": " 분"},
            "steps": [
                {"label": str(t), "method": "animate",
                 "args": [[str(t)], {"frame": {"duration": 0, "redraw": True}, "mode": "immediate"}]}
                for t in steps
            ],
        }],
    )
    # matplotlib origin="lower"와 동일 방향 (행0=하단). 격자 비율 1:1, 축 눈금 숨김.
    fig.update_yaxes(scaleanchor="x", constrain="domain", showgrid=False, zeroline=False,
                     showticklabels=False)
    fig.update_xaxes(constrain="domain", showgrid=False, zeroline=False, showticklabels=False)
    return style_fig(fig, height=560)


def run():
    """ M2 모듈 메인 실행 함수"""
    st.sidebar.header("⚙️ 시뮬레이션 설정")

    try:
        bfs_engine = init_simulation_engine()
        ca_engine = CellularAutomataModel(bfs_engine.width, bfs_engine.height)

        # UI 컴포넌트 배치
        start_node = st.sidebar.number_input(
            "발화점 그래프 노드 ID (0~255)", min_value=0, max_value=224, value=100
        )
        wind_direction = st.sidebar.selectbox(
            "기상 조건 (바람 방향)", ["무풍", "북풍", "남풍", "동풍", "서풍"]
        )
        max_time = st.sidebar.slider("최대 시뮬레이션 시간 (BFS 제한 시간)", 5, 30, 15)
        ca_turns = st.sidebar.slider("셀룰러 오토마타 예측 턴 (CA 반복 횟수)", 1, 10, 3)

        run_btn = st.sidebar.button("▶ 시뮬레이션 실행", key="spread_run_btn", type="primary", use_container_width=True)

        if run_btn:
            with st.spinner("🔥 재난 확산 시뮬레이션 연산 중..."):
                # 1단계: 인구 가중치 기반 기본 BFS 수행 (불길 도달 시간 맵 생성)
                fire_time_map = bfs_engine.run_bfs(
                    start_node_id=f"node_{start_node:03d}", max_time=max_time
                )

                # 2단계: BFS 시간 맵을 CA용 '위험도 레벨 격자(0~3)'로 변환
                current_grid = np.zeros_like(fire_time_map, dtype=int)
                burned_mask = fire_time_map != -1.0

                if np.any(burned_mask):
                    max_t = np.max(fire_time_map[burned_mask])

                    # [성능 최적화] 3600번 도는 느린 2중 for문 대신 Numpy 고속 벡터 연산 적용
                    condlist = [
                        fire_time_map == -1.0,
                        fire_time_map <= max_t * 0.33,
                        fire_time_map <= max_t * 0.66
                    ]
                    choicelist = [0, 3, 2] # 순서대로 안전(0), 재난(3), 위험(2)

                    # 조건에 해당하지 않는 외곽 지역은 기본값 1(주의) 처리
                    current_grid = np.select(condlist, choicelist, default=1)

                # 3단계: 셀룰러 오토마타(CA) 알고리즘으로 설정한 턴 수만큼 바람 조건 반영 및 전파
                final_hazard_map = np.copy(current_grid)
                for _ in range(ca_turns):
                    final_hazard_map = ca_engine.cellular_automata_step(
                        final_hazard_map, wind_dir=wind_direction
                    )

            from core.data_loader import DataLoader as _DL
            _loader = _DL()
            _risk_map: dict = {}
            for _n in _loader.nodes:
                _gx = _n.get("grid_x", 0)
                _gy = _n.get("grid_y", 0)
                if 0 <= _gy < final_hazard_map.shape[0] and 0 <= _gx < final_hazard_map.shape[1]:
                    _risk_map[_n["id"]] = round(float(final_hazard_map[_gy, _gx]) / 3.0, 4)
            st.session_state["risk_map"] = _risk_map

            st.divider()
            st.subheader("📊 결과")
            # 결과 시각화 레이아웃 분할 (좌측: 그래프, 우측: 통계)
            col1, col2 = st.columns([2, 1])

            with col1:
                st.subheader(f"📊 예측 분석 보고서 (발화 노드 ID: {start_node})")
                st.caption("▶ 재생 버튼으로 시간에 따른 확산을 재생하거나, 슬라이더로 특정 시점을 확인하세요.")
                anim = _build_spread_animation(fire_time_map, bfs_engine.population_matrix, max_time)
                show(anim)

            with col2:
                st.subheader("📈 위험 구역 요약")
                # 위험 단계별 셀 개수 카운트하여 리포트 제공
                safe_cnt = np.sum(final_hazard_map == 0)
                watch_cnt = np.sum(final_hazard_map == 1)
                warn_cnt = np.sum(final_hazard_map == 2)
                danger_cnt = np.sum(final_hazard_map == 3)

                st.metric("🚨 최고 재난 구역 (Level 3)", f"{danger_cnt} 칸")
                st.metric("🔥 위험 구역 (Level 2)", f"{warn_cnt} 칸")
                st.metric("⚠️ 주의 구역 (Level 1)", f"{watch_cnt} 칸")
                st.metric("🛡️ 안전 구역 (Level 0)", f"{safe_cnt} 칸")

            # 🔗 타 팀원(M1, M5)들을 위한 데이터 스트림 터미널 구조 출력
            st.info(
                "💡 [연동 정보] 각 격자점 정보는 node_id = (y * 60) + x 수식에 의해 타 모듈과 1:1 매핑 연동됩니다."
            )
        else:
        # 실행 전 빈 화면: 피드백 반영 '모듈 안내 카드' 렌더링
            st.write("") 
            render_module_guide("M2")

    except Exception as e:
        st.error(
            f"🚨 데이터 셋업 에러: 전처리 파일(data/graph_data.json)을 먼저 로드해 주세요. 상세 내용: {e}"
        )

# 이 파일이 단독으로 실행될 때만 화면을 띄우도록 설정 (테스트용)
if __name__ == "__main__":
    run()