# -*- coding: utf-8 -*-
"""cellular_automata.ipynb

Automatically generated by Colab.
"""

# module_m2_spread/cellular_automata.py
import numpy as np

class CellularAutomataModel:

    def __init__(self, width=60, height=60):
        self.width = width
        self.height = height

    def cellular_automata_step(self, current_grid: np.ndarray, wind_dir="무풍") -> np.ndarray:
        """
        [알고리즘] 셀룰러 오토마타(CA) 규칙 기반 다음 단계 격자 상태 계산
        - 이웃 셀들의 위험도(바람 가중치 반영) 평균이 임계값(Threshold)을 초과하면 현재 셀의 위험도 상승
        """
        # CA의 기본: 이전 단계 격자를 복사하여 '다음 단계 격자'를 새로 만듦 (동시성 확보)
        next_grid = current_grid.copy()

        # 8방향 이웃 오프셋 (Moore 이웃)
        directions = [
            (-1, 0), (1, 0), (0, -1), (0, 1),      # 상하좌우
            (-1, -1), (-1, 1), (1, -1), (1, 1)     # 대각선
        ]

        # [전이 규칙] 바람 방향에 따른 이웃 영향도 가중치 설정 (기본값 1.0)
        wind_weights = {d: 1.0 for d in directions}
        if wind_dir == "북풍":
            wind_weights[(-1, 0)] = 2.0  # 북쪽 이웃이 불타고 있으면, 바람 타고 남쪽(나)으로 더 강하게 번짐
            wind_weights[(-1, -1)] = 1.5
            wind_weights[(-1, 1)] = 1.5
        elif wind_dir == "남풍":
            wind_weights[(1, 0)] = 2.0   # 남쪽 이웃이 불타고 있으면, 바람 타고 북쪽(나)으로 더 강하게 번짐
            wind_weights[(1, -1)] = 1.5
            wind_weights[(1, 1)] = 1.5
        elif wind_dir == "서풍":
            wind_weights[(0, -1)] = 2.0  # 서쪽 이웃의 영향력 증가
        elif wind_dir == "동풍":
            wind_weights[(0, 1)] = 2.0   # 동쪽 이웃의 영향력 증가

        # 임계값 설정 (이웃 위험도 가중 평균이 이 값을 넘으면 전파 시작)
        THRESHOLD = 1.2

        # 전 격자 순회
        for y in range(self.height):
            for x in range(self.width):
                # 이미 최고 재난 단계(3)인 셀은 계산 생략
                if current_grid[y, x] >= 3:
                    continue

                neighbor_sum = 0.0
                valid_neighbors = 0

                for dy, dx in directions:
                    ny, nx = y + dy, x + dx

                    # 격자 경계선 내부 검사
                    if 0 <= ny < self.height and 0 <= nx < self.width:
                        # 이웃의 위험도 레벨 가져오기
                        neighbor_hazard = current_grid[ny, nx]

                        # 바람 가중치 적용
                        weight = wind_weights.get((dy, dx), 1.0)
                        neighbor_sum += neighbor_hazard * weight
                        valid_neighbors += 1

                if valid_neighbors > 0:
                    # 이웃들의 가중 평균 위험도 계산
                    neighbor_average = neighbor_sum / valid_neighbors

                    # [상태 전이 규칙] 이웃의 평균 위험도가 임계값을 넘으면 내 위험도 1단계 상승
                    if neighbor_average >= THRESHOLD:
                        next_grid[y, x] = min(current_grid[y, x] + 1, 3)

        return next_grid
