# -*- coding: utf-8 -*-
"""init_grid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbcDastdr75MUdaURj-GDO0YkUcT-wiV
"""

import numpy as np

def init_grid(rows: int, cols: int) -> np.ndarray:
    """
    [자료구조: 2D 격자]
    초기 안전 격자(모든 값을 0으로) 생성.

    상태 가이드라인:
    0 = 안전 (Safe)
    1 = 주의 (Watch)
    2 = 위험 (Warning)
    3 = 재난 발생/최고 위험 (Disaster)
    """
    # rows x cols 크기의 2차원 배열을 만들고 전부 0으로 채웁니다.
    return np.zeros((rows, cols), dtype=int)