# -*- coding: utf-8 -*-
"""ui_spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXSJ7EzOEA7qW7IasBfey-ZLkSkUzutD
"""

# module_m2_spread/ui_spread.py
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# 같은 패키지 폴더 내의 모듈들 로드 (상대 경로로 안전하게 변경)
from .bfs_spread import BFSFireSpread
from .cellular_automata import CellularAutomataModel

# 데이터 로드 캐싱 (성능 최적화)
@st.cache_resource
def init_simulation_engine():
    # 전처리 완료된 데이터 경로 지정 (실제 경로에 맞게 팀원들과 조율 가능)
    return BFSFireSpread("data/graph_data.json")

def run():
    """ M2 모듈 메인 실행 함수"""
    st.title("🔥 M2 화재 위험 구역 확산 예측 대시보드")
    st.sidebar.header("🕹️ 시뮬레이션 제어 환경")

    try:
        bfs_engine = init_simulation_engine()
        ca_engine = CellularAutomataModel(bfs_engine.width, bfs_engine.height)

        # UI 컴포넌트 배치
        start_node = st.sidebar.number_input(
            "발화점 그래프 노드 ID (0~3599)", min_value=0, max_value=3599, value=1830
        )
        wind_direction = st.sidebar.selectbox(
            "기상 조건 (바람 방향)", ["무풍", "북풍", "남풍", "동풍", "서풍"]
        )
        max_time = st.sidebar.slider("최대 시뮬레이션 시간 (BFS 제한 시간)", 5, 30, 15)
        ca_turns = st.sidebar.slider("셀룰러 오토마타 예측 턴 (CA 반복 횟수)", 1, 10, 3)

        if st.sidebar.button("시뮬레이션 가동"):
            with st.spinner("🔥 재난 확산 시뮬레이션 연산 중..."):
                # 1단계: 인구 가중치 기반 기본 BFS 수행 (불길 도달 시간 맵 생성)
                fire_time_map = bfs_engine.run_bfs(
                    start_node_id=start_node, max_time=max_time
                )

                # 2단계: BFS 시간 맵을 CA용 '위험도 레벨 격자(0~3)'로 변환
                current_grid = np.zeros_like(fire_time_map, dtype=int)
                burned_mask = fire_time_map != -1.0

                if np.any(burned_mask):
                    max_t = np.max(fire_time_map[burned_mask])

                    # [성능 최적화] 3600번 도는 느린 2중 for문 대신 Numpy 고속 벡터 연산 적용
                    condlist = [
                        fire_time_map == -1.0,
                        fire_time_map <= max_t * 0.33,
                        fire_time_map <= max_t * 0.66
                    ]
                    choicelist = [0, 3, 2] # 순서대로 안전(0), 재난(3), 위험(2)

                    # 조건에 해당하지 않는 외곽 지역은 기본값 1(주의) 처리
                    current_grid = np.select(condlist, choicelist, default=1)

                # 3단계: 셀룰러 오토마타(CA) 알고리즘으로 설정한 턴 수만큼 바람 조건 반영 및 전파
                final_hazard_map = np.copy(current_grid)
                for _ in range(ca_turns):
                    final_hazard_map = ca_engine.cellular_automata_step(
                        final_hazard_map, wind_dir=wind_direction
                    )

            # 결과 시각화 레이아웃 분할 (좌측: 그래프, 우측: 통계)
            col1, col2 = st.columns([2, 1])

            with col1:
                st.subheader(f"📊 예측 분석 보고서 (발화 노드 ID: {start_node})")

                # 시각화를 위한 마스킹 처리 (0인 안전구역은 투명하게 처리)
                plot_map = final_hazard_map.astype(float)
                plot_map[plot_map == 0] = np.nan

                # 매트릭스 렌더링
                fig, ax = plt.subplots(figsize=(8, 7))

                # 바탕에 은은하게 인구 배경 깔아주기
                ax.imshow(bfs_engine.population_matrix, cmap="gray", alpha=0.15, origin="lower")

                # 그 위에 최종 위험도 격자 얹기
                im = ax.imshow(plot_map, cmap="YlOrRd", vmin=1, vmax=3, origin="lower")

                # 컬러바 가독성 업그레이드
                cbar = plt.colorbar(im, ax=ax, ticks=[1, 2, 3])
                cbar.ax.set_yticklabels(['1 (주의)', '2 (위험)', '3 (재난)'])
                cbar.set_label("최종 위험도 단계 (Hazard Level)")

                ax.set_xlabel("격자 X 좌표")
                ax.set_ylabel("격자 Y 좌표")
                st.pyplot(fig)

            with col2:
                st.subheader("📈 위험 구역 요약")
                # 위험 단계별 셀 개수 카운트하여 리포트 제공
                safe_cnt = np.sum(final_hazard_map == 0)
                watch_cnt = np.sum(final_hazard_map == 1)
                warn_cnt = np.sum(final_hazard_map == 2)
                danger_cnt = np.sum(final_hazard_map == 3)

                st.metric("🚨 최고 재난 구역 (Level 3)", f"{danger_cnt} 칸")
                st.metric("🔥 위험 구역 (Level 2)", f"{warn_cnt} 칸")
                st.metric("⚠️ 주의 구역 (Level 1)", f"{watch_cnt} 칸")
                st.metric("🛡️ 안전 구역 (Level 0)", f"{safe_cnt} 칸")

            # 🔗 타 팀원(M1, M5)들을 위한 데이터 스트림 터미널 구조 출력
            st.info(
                "💡 [연동 정보] 각 격자점 정보는 node_id = (y * 60) + x 수식에 의해 타 모듈과 1:1 매핑 연동됩니다."
            )

    except Exception as e:
        st.error(
            f"🚨 데이터 셋업 에러: 전처리 파일(data/graph_data.json)을 먼저 로드해 주세요. 상세 내용: {e}"
        )

# 이 파일이 단독으로 실행될 때만 화면을 띄우도록 설정 (테스트용)
if __name__ == "__main__":
    run()