# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vffJ_BgzGJLTYmGcE3MTI2oD_UtF5r9k
"""

# ==========================================
# preprocess.py
# 민방위 대피소 + 병원 + 생활인구 데이터를
# 시뮬레이션용 JSON으로 변환하는 전처리 스크립트
#
# 데이터 출처:
#   - 생활인구: 서울특별시 250M격자 생활인구(내국인)
#               https://data.seoul.go.kr/dataList/OA-22784/S/1/datasetView.do
#   - 대피소:   서울시 민방위 대피시설 현황
#   - 병원:     공공데이터포털 병원 인허가 정보
#   - 도로망:   국토교통부 MOCT_LINK.shp (노드링크)
#
# 시뮬레이션 대상 지역 — 아래 REGION 파라미터와 입력 CSV만 교체하면 타 지역 적용 가능
# 타 지역 적용 시 통계청 SGIS 100m 격자로 대체 가능 (동일 구조)
# ==========================================

REGION = "송파구"

import json
import math
import os
import pandas as pd
import geopandas as gpd
try:
    import geopandas as gpd
except ImportError:
    pass
from pyproj import Transformer

# ==========================================
# [공간 정의] 서울시 송파구 실제 위경도 바운딩 박스
# REGION 변경 시 아래 4개 값도 함께 수정
# ==========================================
SONGPA_MIN_LAT, SONGPA_MAX_LAT = 37.4600, 37.5420
SONGPA_MIN_LNG, SONGPA_MAX_LNG = 127.0650, 127.1600
GRID_SIZE = 60

# ==========================================
# [확정] 서울시 250m 격자 UTM-K 오프셋 상수
# REGION 변경 시 역산 필요 (preprocess.py 주석 참고)
# ==========================================
GRID_OFFSET_X = 899780
GRID_OFFSET_Y = 1899427

try:
    pop_transformer = Transformer.from_crs("epsg:5179", "epsg:4326", always_xy=True)
except Exception as e:
    print(f"⚠️ EPSG:5179 변환기 초기화 실패: {e}")
    pop_transformer = None

try:
    transformer = Transformer.from_crs("epsg:5174", "epsg:4326", always_xy=True)
except Exception:
    transformer = Transformer.from_crs("epsg:5186", "epsg:4326", always_xy=True)

def to_grid_cell_real(lat, lng):
    grid_x = int(((lng - SONGPA_MIN_LNG) / (SONGPA_MAX_LNG - SONGPA_MIN_LNG)) * (GRID_SIZE - 1))
    grid_y = int(((lat - SONGPA_MIN_LAT) / (SONGPA_MAX_LAT - SONGPA_MIN_LAT)) * (GRID_SIZE - 1))
    grid_x = max(0, min(GRID_SIZE - 1, grid_x))
    grid_y = max(0, min(GRID_SIZE - 1, grid_y))
    return grid_x, grid_y

def get_haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat/2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2)**2
    return round(R * math.atan2(math.sqrt(a), math.sqrt(1-a)) * 2, 2)

def load_csv_with_encoding(filename):
    encodings = ['cp949', 'utf-8-sig', 'euc-kr', 'utf-8']
    for enc in encodings:
        try:
            df = pd.read_csv(filename, encoding=enc)
            print(f"📖 '{filename}' 파일을 [{enc}] 인코딩으로 성공적으로 읽었습니다.")
            return df
        except UnicodeDecodeError:
            continue
    raise Exception(f"❌ '{filename}' 인코딩 로드 실패")

def build_population_density_map(pop_csv_path):
    """
    서울시 250m 격자 생활인구 CSV 기반 밀도 맵 구축.

    '250M격자' 컬럼 형식: '다사52255325'
      - 한글 접두어: 지역 코드 (무시)
      - 앞 4자리 숫자 × 10 + GRID_OFFSET_X = UTM-K easting
      - 뒤 4자리 숫자 × 10 + GRID_OFFSET_Y = UTM-K northing

    REGION 변경 시:
      1. 해당 지역 바운딩박스 최솟값 위경도를 UTM-K로 역산
      2. 격자코드 최솟값 인덱스와의 차이로 GRID_OFFSET_X/Y 재계산
    """
    density_map = {}

    try:
        pop_df = load_csv_with_encoding(pop_csv_path)

        # 송파구 행정동코드 필터링 (11710)
        # REGION 변경 시 행정동코드 앞 5자리도 함께 수정
        if '행정동코드' in pop_df.columns:
            pop_df = pop_df[pop_df['행정동코드'].astype(str).str.startswith('11710')]
        elif '자치구명' in pop_df.columns:
            pop_df = pop_df[pop_df['자치구명'].str.contains(REGION, na=False)]

        if pop_df.empty:
            print(f"⚠️ {REGION} 데이터 없음. 전체 데이터 사용.")
            pop_df = load_csv_with_encoding(pop_csv_path)

        print(f"📊 {REGION} 생활인구 행 수: {len(pop_df)}")

        # '*' 비식별값 → 0 처리
        pop_df['생활인구합계'] = pd.to_numeric(
            pop_df['생활인구합계'].replace('*', '0'), errors='coerce'
        ).fillna(0)

        def parse_grid_code(code):
            digits = ''.join(c for c in str(code).strip() if c.isdigit())
            if len(digits) != 8:
                return None, None
            tm_x = int(digits[:4]) * 10 + GRID_OFFSET_X
            tm_y = int(digits[4:8]) * 10 + GRID_OFFSET_Y
            try:
                lng, lat = pop_transformer.transform(tm_x, tm_y)
                if not (37.0 <= lat <= 38.0 and 126.5 <= lng <= 127.5):
                    return None, None
                return to_grid_cell_real(lat, lng)
            except:
                return None, None

        success, fail = 0, 0
        for _, row in pop_df.iterrows():
            gx, gy = parse_grid_code(row['250M격자'])
            if gx is None:
                fail += 1
                continue
            key = (gx, gy)
            if key not in density_map:
                density_map[key] = {'sum': 0, 'count': 0}
            density_map[key]['sum'] += float(row['생활인구합계'])
            density_map[key]['count'] += 1
            success += 1

        density_map = {
            k: int(v['sum'] / v['count'])
            for k, v in density_map.items()
        }

        print(f"✅ 격자 파싱 완료 — 성공: {success}행, 실패: {fail}행")
        print(f"✅ 인구밀도 격자 맵 구축 완료: {len(density_map)}개 격자 셀")

    except Exception as e:
        print(f"⚠️ 생활인구 CSV 로드 실패: {e}")
        import traceback
        traceback.print_exc()

    return density_map

def get_node_population_density(grid_x, grid_y, density_map, search_radius=2):
    if not density_map:
        return _estimate_density_by_position(grid_x, grid_y)

    if (grid_x, grid_y) in density_map:
        return int(density_map[(grid_x, grid_y)])

    for r in range(1, search_radius + 1):
        neighbors = []
        for dx in range(-r, r + 1):
            for dy in range(-r, r + 1):
                key = (grid_x + dx, grid_y + dy)
                if key in density_map:
                    neighbors.append(density_map[key])
        if neighbors:
            return int(sum(neighbors) / len(neighbors))

    return int(sum(density_map.values()) / len(density_map))

def _estimate_density_by_position(grid_x, grid_y):
    """CSV 데이터 없을 때 위치 기반 추정 (fallback)"""
    if 18 <= grid_x <= 28 and 34 <= grid_y <= 44:
        return 175
    if 26 <= grid_x <= 42 and 18 <= grid_y <= 32:
        return 110
    if 6 <= grid_x <= 20 and 26 <= grid_y <= 44:
        return 120
    if 26 <= grid_x <= 38 and 42 <= grid_y <= 56:
        return 85
    return 90

def make_perfect_songpa_data():
    print(f"🎯 {REGION} 100% 매핑 데이터 최적화 정합 처리를 시작합니다.")

    result_json = {
        "simulation_settings": {
            "grid_width": GRID_SIZE,
            "grid_height": GRID_SIZE
        },
        "nodes": [],
        "edges": [],
        "grid_mapping": {}
    }

    raw_infra = []
    density_map = build_population_density_map('population_songpa.csv')

    # 대피소
    try:
        shelter_df = load_csv_with_encoding('shelter_songpa.csv')
        print(f"🏃‍♂️ {REGION} 대피소 데이터 파싱: 총 {len(shelter_df)}개 분석 중...")
        for idx, row in shelter_df.iterrows():
            if pd.isna(row['위도']) or pd.isna(row['경도']): continue
            lat_str, lng_str = str(row['위도']).strip(), str(row['경도']).strip()
            if lat_str == '' or lng_str == '': continue
            lat, lng = float(lat_str), float(lng_str)
            c, r = to_grid_cell_real(lat, lng)
            capacity_val = int(row['대피가능인원수']) if not pd.isna(row['대피가능인원수']) else 200
            raw_infra.append({
                "name": str(row['민방위대피시설명']), "type": "shelter",
                "lat": round(lat, 4), "lng": round(lng, 4),
                "capacity": capacity_val, "grid_x": c, "grid_y": r
            })
        print(f"✅ 대피소 {len(raw_infra)}개 노드 바인딩 적재 성공!")
    except Exception as e:
        print(f"❌ 대피소 컬럼 매핑 최종 실패: {e}")

    # 병원
    pre_hospital_count = len(raw_infra)
    try:
        hospital_df = load_csv_with_encoding('hospital_songpa.csv')
        print(f"🏥 {REGION} 병원 데이터 파싱: 총 {len(hospital_df)}개 분석 중...")
        for idx, row in hospital_df.iterrows():
            if pd.isna(row['좌표정보(X)']) or pd.isna(row['좌표정보(Y)']): continue
            x_str, y_str = str(row['좌표정보(X)']).strip(), str(row['좌표정보(Y)']).strip()
            if x_str == '' or y_str == '': continue
            tm_x, tm_y = float(x_str), float(y_str)
            lng, lat = transformer.transform(tm_x, tm_y)
            c, r = to_grid_cell_real(lat, lng)
            raw_infra.append({
                "name": str(row['사업장명']), "type": "hospital",
                "lat": round(lat, 4), "lng": round(lng, 4),
                "capacity": int(row['병상수']) if not pd.isna(row['병상수']) else 45,
                "grid_x": c, "grid_y": r
            })
        print(f"✅ 병원 {len(raw_infra) - pre_hospital_count}개 노드 바인딩 적재 성공!")
    except Exception as e:
        print(f"⚠️ 병원 컬럼 매핑 실패: {e}")

    # 노드 빌드
    for i, info in enumerate(raw_infra):
        node_str_id = f"node_{i+1:03d}"
        pop_density = get_node_population_density(
            info["grid_x"], info["grid_y"], density_map
        )
        result_json["nodes"].append({
            "id": node_str_id, "name": info["name"], "type": info["type"],
            "lat": info["lat"], "lng": info["lng"], "capacity": info["capacity"],
            "grid_x": info["grid_x"], "grid_y": info["grid_y"],
            "population_density": pop_density
        })
        result_json["grid_mapping"][node_str_id] = {
            "row": info["grid_y"], "col": info["grid_x"]
        }

    # 엣지 생성
    nodes = result_json["nodes"]
    nodelink_path = 'nodelink/MOCT_LINK.shp'

    if gpd is not None and os.path.exists(nodelink_path):
        try:
            print("🛣️ [노드링크 연동] 전국 데이터에서 송파구 BBox 경계면만 잘라냅니다...")
            songpa_bbox = (SONGPA_MIN_LNG, SONGPA_MIN_LAT, SONGPA_MAX_LNG, SONGPA_MAX_LAT)
            roads = gpd.read_file(nodelink_path, bbox=songpa_bbox)
            if roads.crs is None or roads.crs.to_string() != "EPSG:4326":
                roads = roads.to_crs("EPSG:4326")
            print(f"✂️ 필터링 완료: {REGION} 내 도로 링크 {len(roads)}개 확보.")
            for i in range(len(nodes)):
                for j in range(i + 1, len(nodes)):
                    dist = get_haversine_distance(
                        nodes[i]["lat"], nodes[i]["lng"],
                        nodes[j]["lat"], nodes[j]["lng"]
                    )
                    if dist <= 3.0:
                        line_segment = roads.cx[
                            min(nodes[i]["lng"], nodes[j]["lng"]):max(nodes[i]["lng"], nodes[j]["lng"]),
                            min(nodes[i]["lat"], nodes[j]["lat"]):max(nodes[i]["lat"], nodes[j]["lat"])
                        ]
                        weight_modifier = 0.8 if not line_segment.empty else 1.2
                        result_json["edges"].append({
                            "from": nodes[i]["id"], "to": nodes[j]["id"],
                            "distance": dist, "weight": round(dist * weight_modifier, 2)
                        })
            print(f"✅ 도로 기반 간선 {len(result_json['edges'])}개 결합 완료!")
        except Exception as e:
            print(f"⚠️ 노드링크 연산 실패 (직선거리 대체): {e}")
            for i in range(len(nodes)):
                for j in range(i + 1, len(nodes)):
                    dist = get_haversine_distance(
                        nodes[i]["lat"], nodes[i]["lng"],
                        nodes[j]["lat"], nodes[j]["lng"]
                    )
                    if dist <= 3.0:
                        result_json["edges"].append({
                            "from": nodes[i]["id"], "to": nodes[j]["id"],
                            "distance": dist, "weight": dist
                        })
    else:
        print("💡 MOCT_LINK.shp 없음 — 직선거리 기반 Edges 구축.")
        for i in range(len(nodes)):
            for j in range(i + 1, len(nodes)):
                dist = get_haversine_distance(
                    nodes[i]["lat"], nodes[i]["lng"],
                    nodes[j]["lat"], nodes[j]["lng"]
                )
                if dist <= 3.0:
                    result_json["edges"].append({
                        "from": nodes[i]["id"], "to": nodes[j]["id"],
                        "distance": dist, "weight": dist
                    })

    output_filename = f"{REGION}_simulation_data.json"
    with open(output_filename, "w", encoding="utf-8") as f:
        json.dump(result_json, f, ensure_ascii=False, indent=2)

    print(f"\n✨ [완료] '{output_filename}' 빌드 완료!")
    print(f"   노드 {len(result_json['nodes'])}개 | 간선 {len(result_json['edges'])}개")

if __name__ == "__main__":
    make_perfect_songpa_data()